sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
after_success:
  - npm run semantic-release
env:
  matrix:
  - TEST_CLIENT=selenium:firefox
  - TEST_CLIENT=saucelabs:chrome
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
